### ISSUE TITLE
Error Installing SHAMPOO

### ISSUE THREAD

**Issue by m-elkholy** [bmorris3/shampoo#17]
I downloaded git and performed the first two commands successfully (cloning the git repository then cd shampoo), however the third "install" command produces the following error:

> Shamu@NadeauLab-DHM MINGW64 ~/shampoo (master)
> $ python setup.py install
> Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
> Freezing version number to shampoo\version.py
> running install
> error: can't create or remove files in install directory
> 
> The following error occurred while trying to add or remove files in the
> installation directory:
> 
>     [Errno 13] Permission denied: 'C:\\Program Files\\Anaconda3\\Lib\\site-packages\\test-easy-install-10176.write-test'
> 
> The installation directory you specified (via --install-dir, --prefix, or
> the distutils default setting) was:
> 
>     C:\Program Files\Anaconda3\Lib\site-packages\
> 
> Perhaps your account does not have write access to this directory?  If the
> installation directory is a system-owned directory, you may need to sign in
> as the administrator or "root" account.  If you do not have administrative
> access to this machine, you may wish to choose a different installation
> directory, preferably one that is listed in your PYTHONPATH environment
> variable.
> 
> For information on other options, you may wish to consult the
> documentation at:
> 
>   https://setuptools.readthedocs.io/en/latest/easy_install.html
> 
> Please make the appropriate changes for your system and try again.

I am the administrator on my Windows 10 pc, so I don't understand why it did not work. 
Any Ideas? 

Thanks,
-Marwan

**Comment by bmorris3** [comment]
I don't know why it didn't work either, but typically problems like this can be resolved by adding this flag to the install command: 

```
python setup.py install --user
```

This will install the package such that it's only built on your account, which often dodges permissions issues.

**Comment by m-elkholy** [comment]
Thanks, It worked!

I ran the shampoo.test() command in python and it returned this message:

> ========================== 6 passed in 50.44 seconds ==========================
> Out[2]: 0

Is that a successful test?

Thanks again for your responses!

**Comment by bmorris3** [comment]
Yep, great!
